platform :ios, '7.0'
pod 'AFNetworking'
pod 'Mantle'
pod 'LBBlurredImage'
pod 'HexColors'
pod 'TSMessages'
pod 'ReactiveCocoa'
pod 'Facebook-iOS-SDK'
pod 'MBProgressHUD'
pod 'BiergartenFetcher', :path => '/Users/platzerworld/Specs/BiergartenFetcher/0.0.1'